### ISSUE TITLE
未将某些父类的字段置为null

### ISSUE THREAD

**Issue by imsudo** [mengyunzhi/core#8]
![image](https://user-images.githubusercontent.com/28392885/43749378-6e9cc796-9a26-11e8-9a46-11750018d774.png)
![image](https://user-images.githubusercontent.com/28392885/43749436-ac617068-9a26-11e8-9d9c-a2152111649d.png)
父类字段不为null，会作为查询条件参与查询

**Comment by teacherpan** [comment]
这个昨天晚上修正了。重新拉取下试试

**Comment by imsudo** [comment]
收到

**Comment by teacherpan** [comment]
![image](https://user-images.githubusercontent.com/12424383/43749606-5502717c-9a27-11e8-8fc8-9214fb285e54.png)
https://github.com/mengyunzhi/core/blob/1.5.3.1/core/src/main/java/com/mengyunzhi/core/service/CommonService.java
最新代码如上

**Comment by imsudo** [comment]
已成功拉取
